version: '3.8'

services:
  vue-app:
    container_name: pet_frontend_dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../src:/app
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - vue_network

networks:
  vue_network:
    driver: bridge
